//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicabilitySB
    {
        public int Id { get; set; }
        public int IdDetailSB { get; set; }
        public int idDetail { get; set; }
    
        public virtual Detail DetailSB { get; set; }
        public virtual Detail Detail { get; set; }
    }
}
