//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detail()
        {
            this.Addresses = new HashSet<Address>();
            this.Applicabilities = new HashSet<Applicability>();
            this.ApplicabilityFiles = new HashSet<ApplicabilityFile>();
            this.ApplicabilityNotices = new HashSet<ApplicabilityNotice>();
            this.ApplicabilitySBProducts = new HashSet<ApplicabilitySB>();
            this.ApplicabilitySBDetails = new HashSet<ApplicabilitySB>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string Developer { get; set; }
        public int TypeDetail { get; set; }
        public Nullable<int> IdFile { get; set; }
        public bool Archive { get; set; }
        public string ArchiveNotice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicability> Applicabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicabilityFile> ApplicabilityFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicabilityNotice> ApplicabilityNotices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicabilitySB> ApplicabilitySBProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicabilitySB> ApplicabilitySBDetails { get; set; }
        public virtual FileTable FileTable { get; set; }
    }
}
