//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KD.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notice()
        {
            this.AddressNotices = new HashSet<AddressNotice>();
            this.ApplicabilityNotices = new HashSet<ApplicabilityNotice>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Developer { get; set; }
        public int CountSheets { get; set; }
        public string ChangeCode { get; set; }
        public int IdFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressNotice> AddressNotices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicabilityNotice> ApplicabilityNotices { get; set; }
        public virtual FileTable FileTable { get; set; }
    }
}
